##############################################################################
## Provision foo
## This role executes much of the needed functionality to provision an
## application using an Ansible Playbook Bundle.  Included in the comments
## below are some sample resources for getting started deploying an application
## to OpenShift.
##############################################################################


##############################################################################
## An OpenShift Origin deployment configuration provides a replication
## controller, spins up pods, and also provides the ability to transition from
## one deployment of an image to a new one.
## https://docs.openshift.org/latest/architecture/core_concepts/deployments.html#deployments-and-deployment-configurations
##############################################################################
#- name: create deployment config
#  openshift_v1_deployment_config:
#    name: foo
#    namespace: '{{ namespace }}'
#    labels:
#      app: foo
#      service: foo
#    replicas: 1
#    selector:
#      app: foo
#      service: foo
#    spec_template_metadata_labels:
#      app: foo
#      service: foo
#    containers:
#    - env:
#      image: docker.io/ansibleplaybookbundle/hello-world:latest # replace with your application image
#      name: foo
#      ports:
#      - container_port: 8080
#        protocol: TCP


##############################################################################
## A Kubernetes service serves as an internal load balancer.  It identifies a
## set of replicated pods in order to proxy the connections it receives to them.
## https://docs.openshift.org/latest/architecture/core_concepts/pods_and_services.html#services
##############################################################################
#- name: create foo service
#  k8s_v1_service:
#    name: foo
#    namespace: '{{ namespace }}'
#    labels:
#      app: foo
#      service: foo
#    selector:
#      app: foo
#      service: foo
#    ports:
#      - name: web
#        port: 80
#        target_port: 8080


##############################################################################
## An OpenShift Origin route exposes a service at a host name, so that external
## clients can reach it by name. Each route consists of a name, a service
## selector, and an optional security configuration.
## https://docs.openshift.org/latest/architecture/networking/routes.html
##############################################################################
#- name: create foo route
#  openshift_v1_route:
#    name: foo
#    namespace: '{{ namespace }}'
#    labels:
#      app: foo
#      service: foo
#    to_name: foo
#    spec_port_target_port: web
#
- name: template
  template:
    src: foo.templ.j2
    dest: /tmp/foo.conf

- name: create configmap
  shell: oc create configmap -n "{{ namespace }}" "{{ _apb_service_instance_id }}" --from-file=/tmp/foo.conf


